### ISSUE TITLE
add support for PR filters

### ISSUE THREAD

**Issue by MartinNowak** [edwardloveall/pullfeed#28]
Thinks this could be implemented using GH's [Search Issues](https://developer.github.com/v3/search/#search-issues) API.
I'm particularly interested into tag and user filters, like https://github.com/dlang/phobos/pulls?q=is:open+is:pr+review-requested:MartinNowak+label:stalled.
Ideally this would just be a `?q=` parameter on the pullfeed endpoint as well.

**Comment by edwardloveall** [comment]
Thanks for the idea @MartinNowak. I think it's a good one, but I don't have time at the moment to implement it. There are also a few changes I'd like to make before this one, namely using GitHub's GraphQL api so I'm fetching much less information.

It may take me a while to get there, but if you'd like to take a stab at it, please do!
