### ISSUE TITLE
pullfeed.co is down

### ISSUE THREAD

**Issue by max-arnold** [edwardloveall/pullfeed#39]
![CleanShot 2021-03-29 at 11 47 39](https://user-images.githubusercontent.com/370942/112788224-98e29100-9084-11eb-9da9-e3d85f95b765.png)

**Comment by edwardloveall** [comment]
Oof, thanks @max-arnold. I'll take a look soon.

**Comment by edwardloveall** [comment]
Should be fixed now. Thanks again for letting me know!
